### ISSUE TITLE
Crashes when using zalosdk in an objective-c project

### ISSUE THREAD

**Issue by hw20101101** [VNG-Zalo/ZaloSDK-iOS#10]
xcode: 13.0
mac os：11.6
iPhone 6s - iOS 13.4

` pod 'ZaloSDK' `

```
#import <ZaloSDK/ZaloSDK.h>

@interface AppDelegate ()
 
@end
@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
     
    //The following code crashes:
    [[ZaloSDK sharedInstance] initializeWithAppId:@"10xxxxxxxxxxxxxx0"];
}
```

log：
```
-[ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance 0x28393d680

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance 0x28393d680'

```

The screenshot is below：

<img width="1272" alt="WX20211208-193538@2x" src="https://user-images.githubusercontent.com/9107226/145202027-3d4f5c74-c061-4cb6-9993-c9cf2f3803c3.png">

**Comment by hw20101101** [comment]
Hello, anyone?

**Comment by minhtoantm** [comment]
Could you try to run Example? Is this OK?

**Comment by hw20101101** [comment]
Thank you, after I use your ZaloSDK_Static_4.0.1206.zip, it can be used normally

**Comment by minhtoantm** [comment]
> Thank you, after I use your ZaloSDK_Static_4.0.1206.zip, it can be used normally

Thanks.

**Comment by hw20101101** [comment]
But there is another problem. When I log in using zalo app, the authorization callback function is not executed. My code is as follows

```
AuthenUtils *authenUtils = [[AuthenUtils alloc] init];
    NSString *codeStr = [authenUtils renewPKCECode];
    [[ZaloSDK sharedInstance] authenticateZaloWithAuthenType:ZAZAloSDKAuthenTypeViaZaloAppAndWebView parentController:self codeChallenge:codeStr extInfo:@{@"appVersion": @"1.0.0"} handler:^(ZOOauthResponseObject *response) {
        
        NSLog(@"-->> response:%@", response);  // Not executed here
}];
```

**Comment by minhtoantm** [comment]
> But there is another problem. When I log in using zalo app, the authorization callback function is not executed. My code is as follows
> 
> ```
> AuthenUtils *authenUtils = [[AuthenUtils alloc] init];
> NSString *codeStr = [authenUtils renewPKCECode];
> [[ZaloSDK sharedInstance] authenticateZaloWithAuthenType:ZAZAloSDKAuthenTypeViaZaloAppAndWebView parentController:self codeChallenge:codeStr extInfo:@{@"appVersion": @"1.0.0"} handler:^(ZOOauthResponseObject *response) {
>         
>         NSLog(@"-->> response:%@", response);  // Not executed here
> }];
> ```

Does this issue happen with example?

**Comment by hw20101101** [comment]
Sorry, it turns out that I forgot to handle ZDKApplicationDelegate

**Comment by minhtoantm** [comment]
> Sorry, it turns out that I forgot to handle ZDKApplicationDelegate

You're welcome
