### ISSUE TITLE
Could install new version 4 using cocoapods

### ISSUE THREAD

**Issue by vqminh** [VNG-Zalo/ZaloSDK-iOS#11]
I got this error message when doing "pod install --repo-update"

CocoaPods could not find compatible versions for pod "ZaloSDK":
  In Podfile:
    ZaloSDK (= 4.0.1206)

Searching on https://cocoapods.org/ also show the old version 2

**Comment by minhtoantm** [comment]
> I got this error message when doing "pod install --repo-update"
> 
> CocoaPods could not find compatible versions for pod "ZaloSDK": In Podfile: ZaloSDK (= 4.0.1206)
> 
> Searching on https://cocoapods.org/ also show the old version 2

Can you check it again
![image](https://user-images.githubusercontent.com/5442921/148727142-69fd2b00-f2b0-4b8e-992b-6ab1242bbf0d.png)
