### ISSUE TITLE
Set default đăng nhập bằng số điện thoại 

### ISSUE THREAD

**Issue by thienan7191** [VNG-Zalo/ZaloSDK-iOS#14]
Cho em hỏi là có cách nào để mình set default hiển thị Tab đăng nhập `với số điện thoại` thay vì đăng nhập `với mã QR` không ạ? Em cảm ơn
![IMG_1354](https://user-images.githubusercontent.com/71439314/167760556-f7f06e85-2a74-48df-a127-18694a627126.PNG)

**Comment by minhtoantm** [comment]
Hi @thienan7191 
Hiện tại ZaloSDK đang không support phần này.
Cảm ơn bạn.
