### ISSUE TITLE
Crash app khi thêm framework manual

### ISSUE THREAD

**Issue by phuoclinh** [VNG-Zalo/ZaloSDK-iOS#17]
Hi team,
Mình add 2 framework ZaloSDK và ZaloSDKCoreKit vô app (ko dùng pod)
Đã thêm thông tin  CFBundleURLTypes, LSApplicationQueriesSchemes đầy đủ vào plist
Khi chạy app thì nó văng lỗi 
`-[ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance`
Ngay đoạn code: `ZaloSDK.sharedInstance().initialize(withAppId: Constant.ZALO_APP_ID)`
Cho mình xin cách fix chỗ này
Thanks

**Comment by elhoangvu** [comment]
> Hi team, Mình add 2 framework ZaloSDK và ZaloSDKCoreKit vô app (ko dùng pod) Đã thêm thông tin CFBundleURLTypes, LSApplicationQueriesSchemes đầy đủ vào plist Khi chạy app thì nó văng lỗi `-[ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance` Ngay đoạn code: `ZaloSDK.sharedInstance().initialize(withAppId: Constant.ZALO_APP_ID)` Cho mình xin cách fix chỗ này Thanks

Hi @phuoclinh, bạn nhấn vào **your_project.xcodepoj** > **Build Settings** > **Other Linker Flags**: thêm cờ **-all_load** và thử lại nhé

**Comment by phuoclinh** [comment]
@elhoangvu ngon, thanks bạn
