### ISSUE TITLE
Login Zalo Khi Chưa Cài Ứng Dụng

### ISSUE THREAD

**Issue by vtamnh14** [VNG-Zalo/ZaloSDK-iOS#2]
Chào anh,
Hiện tại em đang làm chức năng login zalo và có một vấn đề như sau ạ.
Khi thiết bị em đã cài zalo thì em đăng nhập bình thường
Nhưng nếu thiết bị em chưa cài zalo thì open 1 screen lên và có thông báo lỗi như sau
"Invalid Parameter
The parameter bndl_id is required."

Mong đợi phản hồi từ phía Zalo.
Em cảm ơn,

**Comment by vtamnh14** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-10-31 at 17 00 52](https://user-images.githubusercontent.com/48425939/67939086-64ef0c00-fc03-11e9-8319-d992ab132950.png)

**Comment by liemvu** [comment]
@vtamnh14  lỗi này do bundle id & app id không trùng khớp với khai báo trên trang developers.zalo.me. Em check lại xem chính xác chưa nhé.

<img width="1382" alt="Screen Shot 2019-11-04 at 14 54 30" src="https://user-images.githubusercontent.com/839686/68106221-7db53580-ff13-11e9-89d2-869967a3dafd.png">

**Comment by vtamnh14** [comment]
Em cảm ơn anh Liem nhé.
