### ISSUE TITLE
[iOS] Undefined symbol: ___isPlatformVersionAtLeast

### ISSUE THREAD

**Issue by thongdn-it** [VNG-Zalo/ZaloSDK-iOS#5]
Mình tích hợp Zalo SDK trên ios thì khi compile bị lỗi:

`
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[ZOSafariLoginViewController initWithURL:callbackSchema:] in ZaloSDK(ZOSafariLoginViewController.o)
      -[ZOSafariLoginViewController dealloc] in ZaloSDK(ZOSafariLoginViewController.o)
      -[ZOSafariLoginViewController showInParentController:] in ZaloSDK(ZOSafariLoginViewController.o)
      -[ZOSafariLoginViewController dismiss] in ZaloSDK(ZOSafariLoginViewController.o)
      -[ZOLoginWebInternalViewController webViewPaddingTop] in ZaloSDK(ZOLoginWebInternalViewController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

:-1: Undefined symbol: ___isPlatformVersionAtLeast

**Comment by liemvu** [comment]
ZaloSDK bản mới nhất cần build bằng Xcode 11. Bạn có thể dùng các bản cũ hơn nếu dùng Xcode 10.
