### ISSUE TITLE
Mở không đúng app khi quay về zalo

### ISSUE THREAD

**Issue by phongnn9x** [VNG-Zalo/ZaloSDK-iOS#9]
Mình gặp vấn đề như này: trên máy cài 2 app dùng chung 1 zalo app id, sau đó tại app A thì mình đăng nhập bằng zalo -> mở app zalo -> thành công thì lại mở app B thay vì mở lại app A.

Nhờ các bạn giúp mình với!

**Comment by minhtoantm** [comment]
> Mình gặp vấn đề như này: trên máy cài 2 app dùng chung 1 zalo app id, sau đó tại app A thì mình đăng nhập bằng zalo -> mở app zalo -> thành công thì lại mở app B thay vì mở lại app A.
> 
> Nhờ các bạn giúp mình với!

Hi bạn.
Hiện tại hiện tại SDK hỗ trợ việc dùng chung zalo app id cho nhiều app có bundle identifier khác nhau.
